version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  keycloak:
    build: ./keycloak
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    external: true
