version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - start-dev
      - --hostname
      - localhost
      - --hostname-strict=false
    networks:
      - app-network
    restart: unless-stopped

volumes:
  keycloak_data:

networks:
  app-network:
    external: true
