services:
  grafana:
    build: .
    container_name: grafana
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    networks:
      - app-network
    restart: unless-stopped

volumes:
  grafana_data:
    driver: local

networks:
  app-network:
    external: true