services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - keycloak
      - anythingllm
      - qdrant
      - prometheus
      - grafana
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true